---

- debug: msg= {{ ansible_distribution }}

- name: Check if Qualys Cloud Agent is Installed Already
  command: systemctl status qualys-cloud-agent
  register: init_status_result
  ignore_errors: yes

- name: Create Directory for Downloading Qualys Cloud Agent
  sudo: yes
  sudo_user: root
  file:
    path: /usr/qualys/
    state: directory
    owner: azureuser
    group: azureuser
    mode: 0777
    recurse: no

- name: Download the file
  azure_rm_storageblob:
    resource_group: testrg
    storage_account_name: testpackerimage
    container: cloudagent
    blob: qualys-cloud-agent.x86_64.rpm
    dest: /usr/qualys/qualys-cloud-agent.x86_64.rpm

# - name: RPM Download Latest Version of Qualys Cloud Agent
#   get_url:
#     url: "{{ URL  }}"
#     dest: /usr/qualys/qualys-cloud-agent.x86_64.rpm
#     mode: 0755
#   when: ansible_distribution == 'Redhat' or ansible_distribution == 'CentOS'

- name: Execute the Installation Script on RPM
  command: rpm -ivh qualys-cloud-agent.x86_64.rpm
  become: yes
  become_method: sudo
  args:
    chdir: /usr/qualys/
  # when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: Execute the Activation Script
  shell: /usr/local/qualys/cloud-agent/bin/qualys-cloud-agent.sh ActivationId="{{ activation_id }}" CustomerId="{{ customer_id }}"
  become: yes
  become_method: sudo
  
- local_action: wait_for host=localhost port=22 state=started