---

- name: Create Directory for Downloading Qualys Cloud Agent
  file:
    path: /usr/qualys/
    state: directory
    owner: azureuser
    group: azureuser
    mode: 0777
    recurse: no

- name: Download the file
  shell: |
     az login --service-principal -u "{{ c_id }}" -p "{{ c_secret }}" --tenant "{{ t_id }}"
     az storage blob download --container-name cloudagent -f /usr/qualys/qualys-cloud-agent.x86_64.rpm  -n qualys-cloud-agent.x86_64.rpm --account-name testpackerimage

- name: Execute the Installation Script on RPM
  command: rpm -ivh qualys-cloud-agent.x86_64.rpm
  args:
    chdir: /usr/qualys/

- name: stop cloud agent 
  service:
    name: qualys-cloud-agent
    state: stopped
    enabled: true
  register: qualys
  
- debug: msg="{qualys.state}}"

- name: Execute the Activation Script
  shell: |
    /usr/local/qualys/cloud-agent/bin/qualys-cloud-agent.sh ActivationId="{{ qa_id }}" CustomerId="{{ qc_id }}"
  when: qualys.state == stopped