---
- name: Install Git and Check CIS role
  hosts: localhost
  become: true
  gather_facts: true

  roles:
    - git
    - centoscis
    - role: cloudagent
      vars:
         qa_id: "{{ activation_id }}"
         qc_id: "{{ customer_id }}"
         c_id: "{{ client_id }}"
         c_secret: "{{ client_secret }}"
         t_id: "{{ tenant_id }}"
